# Generated by Django 5.0.1 on 2024-03-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esrog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('clarity', models.IntegerField()),
                ('odor_strength', models.IntegerField(default=0)),
                ('texture_smoothness', models.IntegerField(default=0)),
                ('ripeness_score', models.IntegerField(default=0)),
            ],
        ),
    ]
