# Generated by Django 5.0.1 on 2024-03-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esrogim', '0002_esrog_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esrog',
            name='image_url',
        ),
    ]
