# Generated by Django 5.0.1 on 2024-03-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esrogim', '0006_esrog_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esrog',
            name='image_url',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAd1g0lcUsdJbWuqcmOp6G8hD4A92kszSVeLFP476S_baPJWzFDSwxAbjDvHhcZ6LQ998&usqp=CAU', max_length=500),
        ),
    ]
