# Generated by Django 5.0.1 on 2024-03-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esrogim', '0007_alter_esrog_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrog',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
