# Generated by Django 5.0.1 on 2024-03-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esrogim', '0008_esrog_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrog',
            name='estimated_rice',
            field=models.IntegerField(default=0),
        ),
    ]
