# Generated by Django 5.0.1 on 2024-03-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esrogim', '0009_esrog_estimated_rice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esrog',
            old_name='estimated_rice',
            new_name='estimated_price',
        ),
    ]
