# Generated by Django 5.0.1 on 2024-03-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esrogim', '0010_rename_estimated_rice_esrog_estimated_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='esrog',
            name='reserved',
            field=models.CharField(default='', max_length=100),
        ),
    ]
