# Generated by Django 5.0.1 on 2024-03-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esrogim', '0011_esrog_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esrog',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='esrog',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/embed/t10Ajcd_G-w', max_length=500),
        ),
    ]
