# Generated by Django 5.0.1 on 2024-03-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esrogim', '0012_remove_esrog_profile_picture_esrog_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esrog',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
